#!/bin/bash

MANIFEST=git://github.com/NezukoOS/manifest.git
BRANCH=eleven

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name AtomicXZ
git config --global user.email achubadyal4@gmail.com

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

rm -rf packages/apps/Settings
git clone --depth=1 https://"$auth"@github.com/NezukoOS/sextings packages/apps/Settings
git clone --depth=1 https://github.com/NezukoOS/packages_apps_Settings_DescendantHealth.git packages/apps/Settings/DescendantHealth
git clone https://github.com/AtomicXZ/device_xiaomi_phoenix -b nezuko device/xiaomi/phoenix
git clone https://github.com/AtomicXZ/kernel_xiaomi_phoenix --depth=1 -b Q kernel/xiaomi/phoenix
git clone https://"$auth"@github.com/AtomicXZ/vendor vendor/xiaomi

